# Generated by Django 6.0.7 on 2026-07-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('alternativa_a', models.CharField(max_length=200)),
                ('alternativa_b', models.CharField(max_length=200)),
                ('alternativa_c', models.CharField(max_length=200)),
                ('alternativa_d', models.CharField(max_length=200)),
                ('correta', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('resposta', models.CharField(blank=True, choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D')], max_length=1, null=True)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='quiz.prova')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
