# Generated by Django 6.0.7 on 2026-07-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('ME', 'Múltipla escolha'), ('DI', 'Discursiva')], default='ME', max_length=2),
        ),
        migrations.AlterField(
            model_name='itemprova',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_a',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_b',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_c',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questao',
            name='alternativa_d',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta',
            field=models.CharField(blank=True, choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D')], default='', max_length=1),
        ),
    ]
